//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Carousel item</summary>
	[PublishedContentModel("carouselItem")]
	public partial class CarouselItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "carouselItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CarouselItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CarouselItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Carousel headline
		///</summary>
		[ImplementPropertyType("carouselHeadline")]
		public IHtmlString CarouselHeadline
		{
			get { return this.GetPropertyValue<IHtmlString>("carouselHeadline"); }
		}

		///<summary>
		/// Carousel image
		///</summary>
		[ImplementPropertyType("carouselImage")]
		public IPublishedContent CarouselImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("carouselImage"); }
		}

		///<summary>
		/// Carousel link
		///</summary>
		[ImplementPropertyType("carouselLink")]
		public IPublishedContent CarouselLink
		{
			get { return this.GetPropertyValue<IPublishedContent>("carouselLink"); }
		}
	}
}
