//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Frontpage</summary>
	[PublishedContentModel("frontPage")]
	public partial class FrontPage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "frontPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FrontPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FrontPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// AboutBodytext
		///</summary>
		[ImplementPropertyType("aboutBodytext")]
		public IHtmlString AboutBodytext
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutBodytext"); }
		}

		///<summary>
		/// AboutHeadline
		///</summary>
		[ImplementPropertyType("aboutHeadline")]
		public IHtmlString AboutHeadline
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutHeadline"); }
		}

		///<summary>
		/// AboutLink
		///</summary>
		[ImplementPropertyType("aboutLink")]
		public IPublishedContent AboutLink
		{
			get { return this.GetPropertyValue<IPublishedContent>("aboutLink"); }
		}

		///<summary>
		/// Environment first
		///</summary>
		[ImplementPropertyType("environmentFirst")]
		public string EnvironmentFirst
		{
			get { return this.GetPropertyValue<string>("environmentFirst"); }
		}

		///<summary>
		/// Environment image
		///</summary>
		[ImplementPropertyType("environmentImage")]
		public IPublishedContent EnvironmentImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("environmentImage"); }
		}

		///<summary>
		/// Environment second
		///</summary>
		[ImplementPropertyType("environmentSecond")]
		public string EnvironmentSecond
		{
			get { return this.GetPropertyValue<string>("environmentSecond"); }
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return this.GetPropertyValue<string>("headline"); }
		}

		///<summary>
		/// Headline second
		///</summary>
		[ImplementPropertyType("headlineSecond")]
		public string HeadlineSecond
		{
			get { return this.GetPropertyValue<string>("headlineSecond"); }
		}
	}
}
