//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1070 with alias "hideInNav"
	/// <summary>Hide in nav</summary>
	public partial interface IHideInNav : IPublishedContent
	{
		/// <summary>Hide in menu?</summary>
		bool HideInUmbracoMenu { get; }
	}

	/// <summary>Hide in nav</summary>
	[PublishedContentModel("hideInNav")]
	public partial class HideInNav : PublishedContentModel, IHideInNav
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hideInNav";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HideInNav(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HideInNav, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hide in menu?
		///</summary>
		[ImplementPropertyType("hideInUmbracoMenu")]
		public bool HideInUmbracoMenu
		{
			get { return GetHideInUmbracoMenu(this); }
		}

		/// <summary>Static getter for Hide in menu?</summary>
		public static bool GetHideInUmbracoMenu(IHideInNav that) { return that.GetPropertyValue<bool>("hideInUmbracoMenu"); }
	}
}
