//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Service items</summary>
	[PublishedContentModel("serviceItems")]
	public partial class ServiceItems : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "serviceItems";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ServiceItems(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ServiceItems, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Service item bodytext
		///</summary>
		[ImplementPropertyType("serviceItemBodytext")]
		public string ServiceItemBodytext
		{
			get { return this.GetPropertyValue<string>("serviceItemBodytext"); }
		}

		///<summary>
		/// Service item headline
		///</summary>
		[ImplementPropertyType("serviceItemHeadline")]
		public string ServiceItemHeadline
		{
			get { return this.GetPropertyValue<string>("serviceItemHeadline"); }
		}

		///<summary>
		/// Service item link
		///</summary>
		[ImplementPropertyType("serviceItemLink")]
		public IPublishedContent ServiceItemLink
		{
			get { return this.GetPropertyValue<IPublishedContent>("serviceItemLink"); }
		}
	}
}
