//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1081 with alias "visEkstraSection"
	/// <summary>Vis ekstra section</summary>
	public partial interface IVisEkstraSection : IPublishedContent
	{
		/// <summary>Show contact section?</summary>
		bool ShowContactSection { get; }

		/// <summary>Show mobilepay?</summary>
		bool ShowMobilepay { get; }
	}

	/// <summary>Vis ekstra section</summary>
	[PublishedContentModel("visEkstraSection")]
	public partial class VisEkstraSection : PublishedContentModel, IVisEkstraSection
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "visEkstraSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public VisEkstraSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<VisEkstraSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Show contact section?
		///</summary>
		[ImplementPropertyType("showContactSection")]
		public bool ShowContactSection
		{
			get { return GetShowContactSection(this); }
		}

		/// <summary>Static getter for Show contact section?</summary>
		public static bool GetShowContactSection(IVisEkstraSection that) { return that.GetPropertyValue<bool>("showContactSection"); }

		///<summary>
		/// Show mobilepay?
		///</summary>
		[ImplementPropertyType("showMobilepay")]
		public bool ShowMobilepay
		{
			get { return GetShowMobilepay(this); }
		}

		/// <summary>Static getter for Show mobilepay?</summary>
		public static bool GetShowMobilepay(IVisEkstraSection that) { return that.GetPropertyValue<bool>("showMobilepay"); }
	}
}
